### ISSUE TITLE
[Messaging] Connector-Developer: no more building multipart messages

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-Messaging-Services#11]
Currently, the connector developer typically builds a multipart-body-message with header and payload to pass the multipart-body on to us with the recipient info.

Since we will soon be supporting different transmission protocols, a general approach is needed here to become protocol-independent at this point for the connector-developer.

**Comment by vdakker** [comment]
Linked to https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/issues/134 for standard connector to connector communication.
