### ISSUE TITLE
[Wiki] Update Application-Properties page

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-Messaging-Services#111]
Needs to be updated to list all available properties:
https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/7.-Settings:-Application-Properties

**Comment by vdakker** [comment]
https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/6.-Settings:-Application-Properties

all properties currently avaliable on the dev branch are listed on this page
