### ISSUE TITLE
[ClearingHouse] Check against preliminary specification

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-Messaging-Services#119]
Since Monday, a preliminary version of a specification of the communication to the ClearingHouse is available, here we have to check whether we already fulfill this or whether we have to make adjustments again.

https://github.com/International-Data-Spaces-Association/IDS-G-pre/tree/clearinghouse/Components/ClearingHouse

**Comment by stefkoslowski** [comment]
Appraoch for paths of clearing house:
Provide two additional fields in application.properties with URL for the query and logging endpoint which can be optionally set by the user.
If these fields are empty the clearing house url is extended by the paths as specified in IDS-G
