### ISSUE TITLE
[Messaging] Deserialize incoming message

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-Messaging-Services#12]
Currently, for implemented connector message-handlers, the complete payload input-stream of an incoming message is passed to the connector(-developer). Thus the Unified-Lib is independent of the IDS-MessageType of the incoming message, however, the connector developer must then deserialize the incoming message for the corresponding message type in the implementation of the connector instead.

It would be desirable to perform all serialization and deserialization in the Unified-Lib instead of leaving this to the connector developer.

**Comment by stefkoslowski** [comment]
Done with the Message and Payload Objects.
