### ISSUE TITLE
[Core] "ids:trustStore" in configmodel.json should be optional

### ISSUE THREAD

**Issue by jschne1der** [International-Data-Spaces-Association/IDS-Messaging-Services#124]
As said in the title, "ids:trustStore" is redundant in some scenarios:
Certificates for server-keys and CAroot are often provided as `*.pem` files. When using docker, a automated keytool call like 
```
keytool -import -storepass changeit -noprompt -trustcacerts -alias mkcert_development_ca -file $JAVA_HOME/lib/security/mkCertRootCA.pem -keystore cacerts
```
will integrate a rootCA for dev very nicely. Because the Framework is already able to read certs form the default store, the configmodel.json won't need a second truststore. 

My current workaround:  I've configured a truststore with a single dummy cert...

**Comment by tmberthold** [comment]
Moved the feature-request to the IDS-Messaging-Services.

**Comment by tmberthold** [comment]
Now in Pull-Request status, but placed "on hold" because major change. Will be included with the next major version, more details in PR:
https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/pull/130

**Comment by tmberthold** [comment]
Closed due to inactivity. If there is an actual requirement from a use case, we will look into it again.
