### ISSUE TITLE
[Wiki] Add page explaining runtime-options

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-Messaging-Services#147]
Some IDS-Messaging-Services settings are available only at connector-runtime and can be set individually.

Example:
Blacklisting DAT JWT details, like blacklisting all incoming messages of a specific connector or with a DAT issued by a specific DAPS.

Following will automatically block and send RejectionMessages for all incoming IDS-Messages with DATs issued by the AISEC DAPS:

![image](https://user-images.githubusercontent.com/75306992/121032902-01986900-c7ac-11eb-9015-2c7e9a68b91f.png)

**Comment by vdakker** [comment]
https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/6.-Settings:-Connector-Configuration

added runtime options to the Configuration Wiki Page

**Comment by tmberthold** [comment]
Very good!
