### ISSUE TITLE
[Core] DSC / DAPS Issue: "aud": "idsc:IDS_CONNECTORS_ALL"

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-Messaging-Services#153]
For a detailed description, see here:
https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/323

We need to clarify against the DAPS specification, what the DAPS expects.

**Comment by vdakker** [comment]
The [DAPS readme of IDS-G](https://github.com/International-Data-Spaces-Association/IDS-G/blob/master/core/DAPS/README.md) specifies:

| aud | yes | 1 | The audience of the token. This can limit the validity for certain connectors. |
|-----|-----|---|-----------------------------------------------------------------------------|

and uses _https://w3id.org/idsa/code/IDS_CONNECTORS_ALL_ in the examples.

**Comment by tmberthold** [comment]
DAPS currently only accepts this wildcard for me, else it return BAD_REQUEST, will close it here, since it technically works. Needs to be clarified with AISEC DAPS.
