### ISSUE TITLE
Transparent configuration input validation

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-Messaging-Services#173]
Hi all. I have received a feature request that I would like to share with you: 

It would be nice if a syntax check is done before processing (configuration) information and a more meaningful error message is displayed. E.g.: "error parsing json of config" or "invalid value for ids:connectorDeployMode". This should usually be just another if/else or try/catch code block and is very helpful for debugging.

**Comment by juliapampus** [comment]
Didn't know whether to create the issue here or in the framework. Feel free to move/link it.

**Comment by tmberthold** [comment]
I have just tested what happens if there are incorrect values in the configuration, there a pretty good error messages meanwhile:

![image](https://user-images.githubusercontent.com/75306992/130639333-4a515ef7-5431-4f74-a985-0b7504b94741.png)

**Comment by tmberthold** [comment]
Will close this request now, since the error messages issued in the meantime by the infomodel-serializer-parser within the infomodel-serializer provide quite good infos, which value within for example a configuration is faulty and why the config can't be parsed.
