### ISSUE TITLE
Wiki-Page for TEST_DEPLOYMENT vs PRODUCTIVE_DEPLOYMENT

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-Messaging-Services#187]
A wiki page would be helpful for the effects of these two deploy methods, as questions about them come up frequently.

**Comment by vdakker** [comment]
I created a wiki page containing the effects of the ConnectorDeployModes (on the current state of the development branch)

https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/07.-Settings:-Connector-Deploy-Modes
