### ISSUE TITLE
Possible log level changes 

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-Messaging-Services#190]
Using v4.1.1.1. Dataspace Connector in `TEST_DEPLOYMENT` mode. No explicit log settings for the messaging services.

I get the following logs: [20210630_log.txt](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/files/6739853/20210630_log.txt)

It would be nice, if there would be no exception stack with the `error` tag. That unnecessarily fills the logs and may confuse the user when someone intentially uses the connector in test mode. If needed, you could change this to log level `debug`. 

In addition, you could reduce the 4 warnings every time a message is sent to a more compact one. For the same reason, to reduce unnecessary logs. Or you could mark one line as `info`/`warn` and display the others only in `debug` mode.

**Comment by tmberthold** [comment]
Thanks for the feedback, will take a look.

**Comment by tmberthold** [comment]
Future productive deployment error logs:
![image](https://user-images.githubusercontent.com/75306992/123965591-e25cb800-d9b4-11eb-9a50-e89a6d853ee0.png)

Future test deployment warning:
![image](https://user-images.githubusercontent.com/75306992/123965657-f43e5b00-d9b4-11eb-8d3f-f9cc005c5715.png)
