### ISSUE TITLE
Query statement overwritten with null

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-Messaging-Services#197]
@ronjaquensel just had a look into the `BrokerService::queryBroker` method. Seems like the query parameter is not forwarded within the ids multipart message as the payload is only containing a null object. Is this right? Are we missing anything?

**Comment by tmberthold** [comment]
Correct.

Should be fixed with the next version for `queryBroker`
https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/blob/d182efed8d07afa141d261d0b2dc72d7380df079/broker/src/main/java/de/fraunhofer/ids/messaging/broker/BrokerService.java#L202
