### ISSUE TITLE
Enable a Connector to communicate with multiple DAPS (Dataspaces)

### ISSUE THREAD

**Issue by wjost** [International-Data-Spaces-Association/IDS-Messaging-Services#200]
Currently a Connector can only register to one DAPS, hence only be participant at one dataspace. However it would be essential to be able to participate with one connector multiple dataspaces, hence it is necessary to be able to pass the associated DAPS token and/or the address of the associated DAPS with the corresponding request.

**Comment by tmberthold** [comment]
Hello and thank you for the feedback, we will take a look!

**Comment by tmberthold** [comment]
After an initial estimate of the changes needed, this idea will be forwarded internally to the respective architecture groups, as multiple components and concepts would need to be addressed than just the IDS-Messaging-Services to implement this feature request.

**Comment by HeinrichPet** [comment]
IDSA internal ideas of having multiple DAPS: https://industrialdataspace.jiveon.com/docs/DOC-2832

**Comment by tmberthold** [comment]
Will move it to the discussion section, as this requires conceptual changes that we can't address only here in the context of this repo. (Are there then multiple connector certificates from different DAPS etc.?).
