### ISSUE TITLE
No line breaks in source code of logging messages

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/IDS-Messaging-Services#331]
In order to find messages printed in logs, one shall be able to search for the whole string in the IDE, e.g. "TEST_DEPLOYMENT: IDS-Message is sent without a valid DAT, will not be sent...". But this String is not found, due to a line break in the source code:

See `src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java`
```
log.warn(
    "TEST_DEPLOYMENT: IDS-Message is sent without a valid DAT, "
    + "will not be sent in PRODUCTIVE_DEPLOYMENT. [reason=({})]", error);
}
```

**Comment by tmberthold** [comment]
I will create a PR in which we will introduce error codes according to the following scheme, these error-codes can be searched for accordingly:

```
Log Error Codes

format: IMS-XY-L-1234
-> short: IMSXYL1234

IMS = IDS-Messaging-Services
XY = Subsystem Module (CO Core, AP AppStore, BR Broker, CL ClearingHouse, ME Messaging, PA Paris, VO Vocol)
L = Event Severity (E Error, W Warn, I Info, D Debug)
1234 = Error number

will e.g. print as [code=(IMSCOE0001)]  -> IDS-Messaging-Services Core-Module Error 0001
```
