### ISSUE TITLE
[Service-Modules] Use HttpService for sending messages from TokenManagerService and BrokerService or have a Service setting Timeout settings for all HTTP Clients

### ISSUE THREAD

**Issue by vdakker** [International-Data-Spaces-Association/IDS-Messaging-Services#41]
The BrokerService and TokenManagers currently get their own HttpClients from the ClientProvider sending them independently from the HttpService, so their Timeout Settings are always the OkHttp default values. They should use the HttpService, so the Timeouts set there apply to the Broker and DAPS messages, too.

Another way to solve this would be to add a Method to the ClientProvider to override the default Timeouts for all generated Clients (instead of just a method to get an alternative client with other timeout settings once).

**Comment by vdakker** [comment]
This Ticket should be obsolete, BrokerService is using the MessageService, which is using the IdsHttpService.

To use the IdsHttpService in the Tokenmanager we would have to move the http package from Messaging to Core.

**Comment by tmberthold** [comment]
I like "obsolete" issues.
