### ISSUE TITLE
Validate the incoming TLS connection against the incoming DAT

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-Messaging-Services#439]
Currently, the Messaging Services only validates whether the DAT is correct and valid. However, the identity of the sender is not validated.

To do this, the _transportCertsSha256_ from the DAT must be matched with the fingerprint of the TLS certificate.
Therefore the IDS-Messaging Services (and also all other IDS implementations) must dynamically specify their TLS certifacte fingerprint in a DAT request so that the DAT is issued correctly. The DAT is returned only if the identity of the sender has been validated by the DAPS. Therefore, by matching the DAT with the transport certificate fingerprint, we can ensure, that the identity is checked by the DAPS.

Additionally, the hostname specified under _referring Connector_ in the DAT should match the hostname of the TLS connection. This should also be checked.

**Comment by tmberthold** [comment]
`must dynamically specify their TLS certifacte fingerprint in a DAT request `
Do we already have a claim or other option for this in the DAT request? If not, it would have to be added.

**Comment by tmberthold** [comment]
I think it's an ongoing discussion?!
https://github.com/Fraunhofer-AISEC/omejdn-server/issues/38

**Comment by tmberthold** [comment]
Related:
- https://github.com/International-Data-Spaces-Association/omejdn-daps/issues/21
- https://github.com/International-Data-Spaces-Association/omejdn-daps/issues/22

**Comment by tmberthold** [comment]
Waiting for a reference implementation in EDC as this is on the schedule there for current milestone planning. Will then adapt that here when the solution is available.

**Comment by bellebaum** [comment]
For reference, here is the current proposal for specifying the claims as a request parameter (private repo):
https://github.com/International-Data-Spaces-Association/IDS-G-pre/pull/84

**Comment by tmberthold** [comment]
Here's the link to the EDC issue, which is part of the Milestone 4 for the end of the month:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1152
