### ISSUE TITLE
IAIS EIS dependencies

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-Messaging-Services#550]
Currently 
```
<dependency>
            <groupId>de.fraunhofer.iais.eis.ids</groupId>
            <artifactId>interaction</artifactId>
            <version>5.0.0</version>
...
```
is included only for SHACL validation. But this lib brings some more depencencies with it, namely e.fraunhofer.iais.eis.ids:connector-commons:jar:5.0.0 and de.fraunhofer.iais.eis.ids:core:jar. Which are IAIS non-open source libs currently. It would be nice to either move SHACL validation into the Messaging Services or let the IAIS create an extra lib for SHACL validation that can be included here but comes without the unnecessary IAIS dependencies.

**Comment by sebplorenz** [comment]
Btw. for SHACL Validation https://github.com/International-Data-Spaces-Association/InformationModelUtils

**Comment by ghost** [comment]
I will clarify this internally, however, this is probably more something for the colleagues at IAIS and the non-open source repos.

**Comment by ghost** [comment]
Unfortunately, the referenced `InformationModelUtils` repo is a `private` repo, which makes the code not truly open-source, as the code is viewable only by a closed group of participants. Moving the SHACL-validation code from a private Repo into the public Messaging-Services repo could therefore become problematic without further approval.

![image](https://user-images.githubusercontent.com/75306992/174730970-b864434c-55a9-4629-801b-e99963a38fbf.png)

**Comment by ghost** [comment]
Received internal further approval.

**Comment by ghost** [comment]
Got the information that IAIS is planning to open source the corresponding repos. Will wait accordingly for the time being.
