### ISSUE TITLE
[Appstore] Support Messages to App Store

### ISSUE THREAD

**Issue by stefkoslowski** [International-Data-Spaces-Association/IDS-Messaging-Services#70]

**Comment by stefkoslowski** [comment]
Will stay on branch until App Store is ready.

**Comment by HeinrichPet** [comment]
We need the capability to browse the App Store from DSC side.
Like we do with the metadata Broker.

**Comment by tmberthold** [comment]
Will be available in one of the next releases, functionalities are prepared and need to be further tested.
