### ISSUE TITLE
Different repository locations in README and Wiki, but none can be reached

### ISSUE THREAD

**Issue by EdithBirrer1** [International-Data-Spaces-Association/IDS-Messaging-Services#754]
**Describe the bug**
The README.md of the project and the Wiki list two different repositories. Neither seems to be reachable from public.

**To Reproduce**

Use a Maven-Java project and add the Steps to reproduce the behavior:
1. Add the repository to the pom.xml (see list below)
2. Add the dependency to the pom.xml: 
   ```
   <dependency>
      <groupId>de.fraunhofer.ids.messaging</groupId>
      <artifactId>broker</artifactId>
      <version>7.0.0</version>
   </dependency>
   ``` 
4. try to build the project

The two repository locations:

- Repo according to [current README.md](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/blob/e6da46cbcbbf55bd0cfe1388396d76ae7c67fee2/README.md#step-1) is 
   ```
   <repository>
      <id>sovity-public</id>
      <url>https://pkgs.dev.azure.com/sovity/5bec6cbd-c80a-47ac-86ce-1deb26cee853/_packaging/artifact/maven/v1</url>
   </repository>
   ``` 
   This address (when entered into a browser) responds with the message `{"Info":"Feed 'artifact' root of maven repository"}`, but is then not able to serve the requested dependency.

-  Repo according to [Wiki page 1](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/01.-Getting-Started#step-1) is 
   ```
   <repository>
        <id>isst-nexus-public</id>
        <name>isst-public</name>
        <url>https://mvn.ids.isst.fraunhofer.de/nexus/repository/ids-public/</url>
   </repository>
   ``` 
   This address (when entered into a browser) tekes a while, but then does not respond. It does also not serve the requested repo. 

**Expected behavior**

The dependency can be loaded into the project.

Where is the correct repository for the dependencies?

**Comment by ghost** [comment]
The second repo is definitely deprecated and will not provide version 7.0.0. we will look at the Azure repo.

**Comment by ghost** [comment]
Hi, after a quick check, version 7.0.0 is downloadable from our Azure repo, maybe it was a temporary issue?

For a reference implementation, the pom.xml of the DataSpaceConnector (DSC) can also be viewed.

Downloaded artifcats from azure (7.0.0):
![image](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/assets/75306992/4ae5fb3f-05a8-4c9a-8adf-1ebe7c4bdfca)

```
<repository>
    <id>sovity-public</id>
    <url>https://pkgs.dev.azure.com/sovity/5bec6cbd-c80a-47ac-86ce-1deb26cee853/_packaging/artifact/maven/v1</url>
</repository>
```

```
<dependency>
    <groupId>ids.messaging</groupId>
    <artifactId>broker</artifactId>
    <version>${ids-messaging-services.version}</version>
    ...
```

`<ids-messaging-services.version>7.0.0</ids-messaging-services.version>`

Link to the connector reference implementation:
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/cff7d16598520f25d112988861eed1e29a307cb8/pom.xml#L638

I will update the wiki, if there are still problems, please let me know again.

**Comment by EdithBirrer1** [comment]
Thanks! Trying your response, I found that not only the repositories are/were listed differently in Wiki and README, but also the dependency. The Wiki lists group id as  `<groupId>de.fraunhofer.ids.messaging</groupId>`, the REAMDE has `<groupId>ids.messaging</groupId>`.

In my first trials, I hadn't noticed the difference and tried the Wiki groupId against both repos - which then did not work. So please also update the groupId in the Wiki. 
Now I could download the dependency and can start working with it - thanks!

**Comment by ghost** [comment]
Hello and thank you.
With documentation it behaves like with demo videos: They do not age well. - Has been updated.

**Comment by EdithBirrer1** [comment]
There is more to it... the filters for the component scan in [Getting Started](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/01.-Getting-Started) also need to be adapted (omit "de.fraunhofer"). I don't know what else...

**Comment by ghost** [comment]
Hello and thank you for the feedback again!
We have also adjusted this part as well.
If there is anything else, please just let us know.
